service: tokenize

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  tokens:
    handler: src/tokens.handler
    events:
      - http:
          path: tokens
          method: post
          cors: true

# custom:
#   esbuild:
#     bundle: true
#     minify: true

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'

plugins:
  - serverless-plugin-typescript
  - serverless-offline